FROM python:3.10

WORKDIR /user-sport-app

COPY . .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 8008

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8008", "--reload"]