name: Test coverage

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review
    branches:
      - main
      - develop

jobs:
  ci-test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test and coverage
        working-directory: .
        id: run-test-coverage
        run: |
          pytest --cov=app

      - name: Check coverage
        working-directory: .
        id: check-coverage
        run: |
          COVERAGE_THRESHOLD=85
          coverage=$(coverage report -m | tail -n 1 | awk '{print $4}' | tr -d %)
          if [ $coverage -ge $COVERAGE_THRESHOLD ]; then
            echo "Tests coverage ($coverage%) is greater than or equal to the threshold ($COVERAGE_THRESHOLD%). Tests passed!"
          else
            echo "Tests coverage ($coverage%) is below the threshold ($COVERAGE_THRESHOLD%). Tests failed!"
            exit 1
          fi
